server:
  port: ${vcap.application.port:9098}

spring:
  jpa:
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    hostname: ${APPLICATION_DOMAIN:127.0.0.1}
    nonSecurePort: ${server.port}
